version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: version-control-schedule-backend
    container_name: version-control-schedule-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker-local
      - TZ=Europe/Warsaw
    ports:
      - "8080:8080"
    networks:
      - version-control-schedule-network

  frontend:
    build:
      context: ../version-control-schedule-frontend
      dockerfile: Dockerfile
    image: version-control-schedule-frontend
    container_name: version-control-schedule-frontend
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "3000:3000"
    networks:
      - version-control-schedule-network

networks:
  version-control-schedule-network:
    driver: bridge
